### ISSUE TITLE
Novavax link broken

### ISSUE THREAD

**Issue by miseminger** [nodrogluap/pokay#12] opened 2023-05-11 17:48 UTC
[https://www.novavax.com/sites/default/files/2021-02/20210202-NYAS-Novavax-Final.pdf](https://www.novavax.com/sites/default/files/2021-02/20210202-NYAS-Novavax-Final.pdf) in [S_vaccine_neutralization_efficacy.txt](https://github.com/nodrogluap/pokay/blob/36cbad2b02ee049ef484a4cca0ddebb22f5b3775/data/S_vaccine_neutralization_efficacy.txt#L865)

**Comment by nodrogluap** [comment] 2023-05-11 19:31
Removed with commit [eeca40c](https://github.com/nodrogluap/pokay/commit/eeca40caff2f94a102c910e5aeb4086fac45c44f) as dupe of Shinde et al. (2021)

**Closed as completed by nodrogluap** 2023-05-11 19:31 UTC
